export const matchSeed = [
  {
    opponent: "Mallorca",
    stadium: "Estadi Mallorca Son Moix",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Estadio_de_Son_Moix.jpg",
    image: "/pictures/club-logos/MLL.png",
    date: "08.16.25, 18:30",
    goalOpponent: 0,
    goalBarca: 3,
  },
  {
    opponent: "Levante",
    stadium: "Ciutat de Valencia",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Ciutat_de_Valencia.jpg",
    image: "/pictures/club-logos/LEV.png",
    date: "08.23.25, 20:30",
    goalOpponent: 2,
    goalBarca: 3,
  },
  {
    opponent: "Rayo Vallecano",
    stadium: "Estadio de Vallecas",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Estadio_de_Vallecas.jpg",
    image: "/pictures/club-logos/RAY.png",
    date: "08.31.25, 20:30",
    goalOpponent: 1,
    goalBarca: 1,
  },
  {
    opponent: "Valencia",
    stadium: "Estadi Johan Cruyff",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Estadio_Johan_Cruyff.jpg",
    image: "/pictures/club-logos/VAL.png",
    date: "09.14.25, 20:00",
    goalBarca: 6,
    goalOpponent: 0,
  },
  {
    opponent: "Newcastle",
    stadium: "St.James' Park",
    tournament: "Champions League",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/St._James_Park.jpg",
    image: "/pictures/club-logos/NEW.png",
    date: "09.18.25, 20:00",
    goalOpponent: 1,
    goalBarca: 2,
  },
  {
    opponent: "Getafe",
    stadium: "Estadi Johan Cruyff",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Estadio_Johan_Cruyff.jpg",
    image: "/pictures/club-logos/GET.png",
    date: "09.21.25, 20:00",
    goalBarca: 3,
    goalOpponent: 0,
  },
  {
    opponent: "Real Oviedo",
    stadium: "Carlos Tartiere",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Estadio_Carlos_Tartier.jpg",
    image: "/pictures/club-logos/OVI.png",
    date: "09.25.25, 20:30",
    goalBarca: 3,
    goalOpponent: 1,
  },
  {
    opponent: "Real Sociedad",
    stadium: "Estadi Olímpic Lluís Companys",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Estadio_Olimpic_lluis_Companys.jpg",
    image: "/pictures/club-logos/RSO.png",
    date: "09.28.25, 17:30",
    goalBarca: 2,
    goalOpponent: 1,
  },
  {
    opponent: "PSG",
    stadium: "Estadi Olímpic Lluís Companys",
    tournament: "Champions League",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Estadio_Olimpic_lluis_Companys.jpg",
    image: "/pictures/club-logos/PSG.png",
    date: "10.01.25, 20:00",
    goalBarca: 1,
    goalOpponent: 2,
  },
  {
    opponent: "Sevilla",
    stadium: "Ramón Sánchez-Pizjuán",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Ramon_Sanchez_Pizjuan.jpg",
    image: "/pictures/club-logos/SEV.png",
    date: "10.05.25, 15:15",
    goalBarca: 1,
    goalOpponent: 4,
  },
  {
    opponent: "Girona",
    stadium: "Estadi Olímpic Lluís Companys",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Estadio_Olimpic_lluis_Companys.jpg",
    image: "/pictures/club-logos/GIR.png",
    date: "10.18.25, 15:15",
    goalBarca: 2,
    goalOpponent: 1,
  },
  {
    opponent: "Olympiacos",
    stadium: "Estadi Olímpic Lluís Companys",
    tournament: "Champions League",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Estadio_Olimpic_lluis_Companys.jpg",
    image: "/pictures/club-logos/OLY.png",
    date: "10.21.25, 15:15",
    goalBarca: 6,
    goalOpponent: 1,
  },
  {
    opponent: "Real Madrid",
    stadium: "Santiago Bernabéu",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Santiago_Bernabeu.jpg",
    image: "/pictures/club-logos/RMD.png",
    date: "10.26.25, 15:15",
    goalBarca: 1,
    goalOpponent: 2,
  },
  {
    opponent: "Elche",
    stadium: "Estadi Olímpic Lluís Companys",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Estadio_Olimpic_lluis_Companys.jpg",
    image: "/pictures/club-logos/ELC.png",
    date: "11.02.25, 17:30",
    goalBarca: 3,
    goalOpponent: 1,
  },
  {
    opponent: "Club Bruge",
    stadium: "Jan Breydelstadion",
    tournament: "Champions League",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Jan_Breydel.jpg",
    image: "/pictures/club-logos/BRU.png",
    date: "11.05.25, 20:00",
    goalBarca: 3,
    goalOpponent: 3,
  },
  {
    opponent: "Celta Vigo",
    stadium: "Estadio Abanca-Balaídos",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Estadio_de_Balaidos.jpg",
    image: "/pictures/club-logos/CLV.png",
    date: "11.09.25, 20:00",
    goalBarca: 4,
    goalOpponent: 2,
  },
  {
    opponent: "Athletic Club",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp_Nou.jpg",
    image: "/pictures/club-logos/ATH.png",
    date: "11.22.25, 15:15",
    goalBarca: 4,
    goalOpponent: 0,
  },
  {
    opponent: "Chelsea",
    stadium: "Stamford Bridge",
    tournament: "Champions League",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Stamford_Bridge.jpg",
    image: "/pictures/club-logos/CHE.png",
    date: "11.25.25, 20:00",
    goalBarca: 0,
    goalOpponent: 3,
  },
  {
    opponent: "Deportivo Alaves",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp_Nou.jpg",
    image: "/pictures/club-logos/CDA.png",
    date: "11.29.25, 15:15",
    goalBarca: 3,
    goalOpponent: 1,
  },
  {
    opponent: "Atletico Madrid",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp_Nou.jpg",
    image: "/pictures/club-logos/ATM.png",
    date: "12.02.25, 20:00",
    goalBarca: 3,
    goalOpponent: 1,
  },
  {
    opponent: "Real Betis",
    stadium: "Estadio La Cartuja de Sevilla",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Stadium_La_Cartuja.webp",
    image: "/pictures/club-logos/BET.png",
    date: "12.06.25, 17:30",
    goalBarca: 5,
    goalOpponent: 3,
  },
  {
    opponent: "Eintracht Frankfurt",
    stadium: "Spotify Camp Nou",
    tournament: "Champions League",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp_Nou.jpg",
    image: "/pictures/club-logos/SGE.png",
    date: "12.09.25, 20:00",
    goalBarca: 2,
    goalOpponent: 1,
  },
  {
    opponent: "Osasuna",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp_Nou.jpg",
    image: "/pictures/club-logos/OSA.png",
    date: "12.13.25, 17:30",
    goalBarca: 2,
    goalOpponent: 0,
  },
  {
    opponent: "Deportivo Guadalajara",
    stadium: "Estadio Pedro Escartin",
    tournament: "copa del rey",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Estadio_Pedro_Escartin.webp",
    image: "/pictures/club-logos/GUA.png",
    date: "12.16.25, 21:30",
    goalBarca: 2,
    goalOpponent: 0,
  },
  {
    opponent: "Villareal",
    stadium: "Estadio de la Cerámica",
    tournament: "La Liga",
    isInHome: false,
    
    stadiumImage: "/pictures/stadiums/Estadio_de_La_Ceramica.webp",
    image: "/pictures/club-logos/VIL.png",
    date: "12.21.25, 15:15",
    goalBarca: 2,
    goalOpponent: 0,
  },
  {
    opponent: "Espanyol",
    stadium: "RCDE Stadium",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/RCDE_Stadium.webp",
    image: "/pictures/club-logos/ESP.png",
    date: "01.03.26, 20:00",
    goalBarca: 2,
    goalOpponent: 0,
  },
  {
    opponent: "Athletic Club",
    stadium: "Alinma Stadium",
    tournament: "Supercopa de Espana",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Alinma.webp",
    image: "/pictures/club-logos/ATH.png",
    date: "01.07.26, 20:00",
    goalBarca: 5,
    goalOpponent: 0,
  },
  {
    opponent: "Real Madrid",
    stadium: "Alinma Stadium",
    tournament: "Supercopa de Espana",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Alinma.webp",
    image: "/pictures/club-logos/RMD.png",
    date: "01.11.26, 20:00",
    goalBarca: 3,
    goalOpponent: 2,
  },
  {
    opponent: "Racing Santander",
    stadium: "El Sardinero",
    tournament: "copa del rey",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/El_Sardinero.webp",
    image: "/pictures/club-logos/RAC.png",
    date: "01.16.26, 21:15",
    goalBarca: 2,
    goalOpponent: 0,
  },
  {
    opponent: "Real Sociedad",
    stadium: "Anoeta Stadium",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Anoeta_Stadium.jpg",
    image: "/pictures/club-logos/RSO.png",
    date: "01.18.26, 21:00",
    goalBarca: 1,
    goalOpponent: 2,
  },
  {
    opponent: "Slavia Pragua",
    stadium: "Fortuna Arena",
    tournament: "Champions League",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Fortuna_Arena.webp",
    image: "/pictures/club-logos/SVP.png",
    date: "01.21.26, 21:00",
    goalBarca: 4,
    goalOpponent: 2,
  },
  {
    opponent: "Real Oviedo",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp-Nou.webp",
    image: "/pictures/club-logos/OVI.png",
    date: "01.25.26, 16:15",
    goalBarca: 3,
    goalOpponent: 0,
  },
  {
    opponent: "FC Copenhagen",
    stadium: "Spotify Camp Nou",
    tournament: "Chempions League",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp-Nou.jpg",
    image: "/pictures/club-logos/CPH.png",
    date: "01.25.28, 20:00",
  },
  {
    opponent: "Elche",
    stadium: "Estadio Manuel Martínez Valero",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Estadio_Manuel_Martinez.webp",
    image: "/pictures/club-logos/ELC.png",
    date: "02.01.26, 16:00",
  },

  {
    opponent: "Albacete",
    stadium: "Estadio Carlos Belmonte",
    tournament: "copa del rey",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Estadio_Carlos_Belmonte.webp",
    image: "/pictures/club-logos/ALB.png",
    date: "02.04.26, 21:00",
  },
  {
    opponent: "Mallorca",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp-Nou.jpg",
    image: "/pictures/club-logos/MLL.png",
    date: "02.08.26, 16:00",
  },
  {
    opponent: "Girona",
    stadium: "Estadi Montilivi",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Estadio_Montelivi.webp",
    image: "/pictures/club-logos/GIR.png",
    date: "02.15.26, 16:00",
  },
  {
    opponent: "Levante",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp-Nou.jpg",
    image: "/pictures/club-logos/LEV.png",
    date: "02.22.26, 16:00",
  },
  {
    opponent: "Villareal",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp-Nou.jpg",
    image: "/pictures/club-logos/VIL.png",
    date: "03.01.26, 16:00",
  },
  {
    opponent: "Athletic Club",
    stadium: "San Mamés Stadium ",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/San_Mames_Stadium.webp",
    image: "/pictures/club-logos/ATH.png",
    date: "03.08.26, 16:00",
  },
  {
    opponent: "Sevilla",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp-Nou.jpg",
    image: "/pictures/club-logos/SEV.png",
    date: "03.15.26, 16:00",
  },
  {
    opponent: "Rayo Vallecano",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp-Nou.jpg",
    image: "/pictures/club-logos/RAY.png",
    date: "03.22.26, 16:00",
  },
  {
    opponent: "Atletico Madrid",
    stadium: "Metropolitano Stadium",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Metropolitano_Stadium.webp",
    image: "/pictures/club-logos/ATM.png",
    date: "04.05.26, 16:00",
  },
  {
    opponent: "Espanyol",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp-Nou.jpg",
    image: "/pictures/club-logos/ESP.png",
    date: "04.12.26, 16:00",
  },
  {
    opponent: "Getafe",
    stadium: "Coliseum Stadium",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Coliseum_Stadium.webp",
    image: "/pictures/club-logos/GET.png",
    date: "04.19.26, 16:00",
  },
  {
    opponent: "Celta Vigo",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp-Nou.jpg",
    image: "/pictures/club-logos/CLV.png",
    date: "04.22.26, 20:00",
  },
  {
    opponent: "Osasuna",
    stadium: "Estadio El Sadar",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Estadio_El_Sadar.webp",
    image: "/pictures/club-logos/OSA.png",
    date: "05.03.26, 16:00",
  },
  {
    opponent: "Real Madrid",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp-Nou.jpg",
    image: "/pictures/club-logos/RMD.png",
    date: "05.10.26, 16:00",
  },
  {
    opponent: "Deportivo Alaves",
    stadium: "Mendizorrotza Stadium",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Mendizorroza_Stadium.webp",
    image: "/pictures/club-logos/CDA.png",
    date: "05.13.26, 20:00",
  },
  {
    opponent: "Real Betis",
    stadium: "Spotify Camp Nou",
    tournament: "La Liga",
    isInHome: true,
    stadiumImage: "/pictures/stadiums/Camp-Nou.jpg",
    image: "/pictures/club-logos/BET.png",
    date: "05.17.26, 16:00",
  },
  {
    opponent: "Valencia",
    stadium: "Mestalla Stadium",
    tournament: "La Liga",
    isInHome: false,
    stadiumImage: "/pictures/stadiums/Mestalla_Stadium.webp",
    image: "/pictures/club-logos/VAL.png",
    date: "05.24.26, 16:00",
  },
];