export const playerSeed = [
  // {
  //   name: "Marc-Andre",
  //   surname: "TER STEGEN",
  //   shirtNumber: 1,
  //   position: "goalkeeper",
  //   image: "/pictures/first-team/Ter_Stegen.webp",
  //   appearances: 423,
  //   cleanSheets: 175,
  //   saves: 989,
  // },
  {
    name: "Joan",
    surname: "García",
    shirtNumber: 13,
    position: "Goalkeeper",
    age: 24,
    nationality: "Spain",
    image: "/pictures/first-team/Joan_Garcia.webp",
    biography: [
      "Joan García Pons (born May 4, 2001, in Sallent de Llobregat, Catalonia) is a Spanish professional footballer who plays as a goalkeeper for FC Barcelona.",
      "García began his football journey as an outfield player before transitioning to goalkeeper, inspired by his older brother. He developed through the youth systems of Sallent, Manresa, and Damm before joining Espanyol at age 15.",
      "He made his senior debut for Espanyol B in 2019 and broke into the first team in 2021. García became Espanyol’s starting goalkeeper in the 2023–24 season, helping the club secure promotion to La Liga and earning recognition as one of Spain’s top shot-stoppers.",
      "In the 2024–25 La Liga season, García led the league in saves and prevented more goals than any other goalkeeper, according to advanced metrics. His performances attracted interest from major European clubs.",
      "Barcelona signed García in June 2025 by activating his €25 million release clause. He quickly established himself as the club’s first-choice goalkeeper, debuting in both La Liga and the UEFA Champions League.",
      "García’s 2025–26 season was interrupted by a meniscus injury, but he returned to action in November 2025 and continued to deliver elite performances, leading La Liga in save percentage and goals prevented.",
      "Internationally, García has represented Spain at every youth level and won an Olympic gold medal at the 2024 Paris Games with the U23 team.",
      "Known for his reflexes, composure, and ball-playing ability, García is regarded as one of the most promising goalkeepers in European football.",
    ],
    tags: ["Goalkeeper", "Spain"],
    stats: {
      total: {
        appearances: 29,
        cleanSheets: 12,
        saves: 83,
        goalsConceded: 29,
      },
      seasons: [
        {
          season: "2025/26",
          appearances: 29,
          cleanSheets: 12,
          saves: 83,
          goalsConceded: 29,
        },
      ],
    },
  },
  {
    name: "Wojciech",
    surname: "Szczęsny",
    shirtNumber: 25,
    position: "Goalkeeper",
    age: 35,
    nationality: "Poland",
    image: "/pictures/first-team/Szczesny.webp",
    biography: [
      "Wojciech Tomasz Szczęsny (born 18 April 1990 in Warsaw, Poland) is a Polish professional footballer who plays as a goalkeeper for FC Barcelona. Renowned for his height, athleticism, and leadership, Szczęsny has enjoyed a distinguished career at Arsenal, Roma, Juventus, and Barcelona. After a brief retirement in 2024, he joined Barcelona, quickly becoming a key figure in their domestic treble-winning season. Szczęsny is celebrated for his shot-stopping, composure, and organizational skills, and has earned 84 caps for the Polish national team. In July 2025, he extended his contract with Barcelona until June 2027.",
    ],
    tags: ["Goalkeeper", "Poland"],
    stats: {
      total: {
        appearances: 39,
        cleanSheets: 14,
        saves: 114,
        goalsConceded: 48,
      },
      seasons: [
        {
          season: "2024/25",
          appearances: 30,
          cleanSheets: 14,
          saves: 88,
          goalsConceded: 34,
        },
        {
          season: "2025/26",
          appearances: 9,
          minutes: 810,
          cleanSheets: 0,
          saves: 26,
          goalsConceded: 14,
        },
      ],
    },
  },

  {
    name: "Alejandro",
    surname: "BALDE",
    shirtNumber: 3,
    position: "Defender",
    age: 22,
    nationality: "Spain",
    image: "/pictures/first-team/Balde.webp",
    biography: [
      "Alejandro Balde Martínez (born 18 October 2003 in Barcelona, Spain) is a Spanish professional footballer who plays as a left-back for FC Barcelona.",
      "A product of La Masia, Balde made his first-team debut in 2021 and quickly established himself as the club’s starting left-back.",
      "Known for his pace, dribbling, and attacking runs down the flank, Balde has also represented Spain at senior level, including the 2022 FIFA World Cup.",
    ],
    tags: ["Defender", "Left-back", "Spain", "La Masia"],
    stats: {
      total: {
        appearances: 132,
        goals: 2,
        assists: 11,
      },
      seasons: [
        {
          season: "2021/22",
          appearances: 7,
          goals: 0,
          assists: 0,
        },
        {
          season: "2022/23",
          appearances: 44,
          goals: 1,
          assists: 6,
        },
        {
          season: "2023/24",
          appearances: 28,
          goals: 1,
          assists: 1,
        },
        {
          season: "2024/25",
          appearances: 47,
          goals: 1,
          assists: 8,
        },
        {
          season: "2025/26",
          appearances: 32,
          goals: 0,
          assists: 3,
        },
      ],
    },
  },
  {
    name: "Ronald",
    surname: "ARAUJO",
    shirtNumber: 4,
    position: "Defender",
    age: 26,
    nationality: "Uruguay",
    image: "/pictures/first-team/Araujo.webp",
    biography: [
      "Ronald Federico Araújo da Silva (born 7 March 1999 in Rivera, Uruguay) is a Uruguayan professional footballer who plays as a centre-back for FC Barcelona.",
      "Araújo joined Barcelona B in 2018 and was promoted to the first team in 2020. He quickly became one of the leaders in defense thanks to his strength, aerial ability, and tactical awareness.",
      "He has represented Uruguay at senior level, including the 2022 FIFA World Cup.",
    ],
    tags: ["Defender", "Centre-back", "Uruguay", "La Masia", "Captain"],
    stats: {
      total: {
        appearances: 192,
        goals: 12,
        assists: 7,
      },
      seasons: [
        {
          season: "2019/20",
          appearances: 6,
          goals: 0,
          assists: 0,
        },
        {
          season: "2020/21",
          appearances: 33,
          goals: 2,
          assists: 1,
        },
        {
          season: "2021/22",
          appearances: 43,
          goals: 4,
          assists: 0,
        },
        {
          season: "2022/23",
          appearances: 31,
          goals: 1,
          assists: 2,
        },
        {
          season: "2023/24",
          appearances: 37,
          goals: 1,
          assists: 1,
        },
        {
          season: "2024/25",
          appearances: 25,
          goals: 2,
          assists: 2,
        },
        {
          season: "2025/26",
          appearances: 23,
          goals: 3,
          assists: 0,
        },
      ],
    },
  },
  {
    name: "Pau",
    surname: "CUBARSI",
    shirtNumber: 5,
    position: "Defender",
    age: 19,
    nationality: "Spain",
    image: "/pictures/first-team/Cubarsi.webp",
    biography: [
      "Pau Cubarsí (born 22 January 2007 in Banyoles, Spain) is a Spanish professional footballer who plays as a centre-back for FC Barcelona.",
      "A product of La Masia, Cubarsí made his first-team debut in 2024 at the age of 17, quickly impressing with his composure, anticipation, and ball-playing ability.",
      "He is considered one of the brightest defensive talents of his generation and has already represented Spain at youth international levels.",
    ],
    tags: ["Defender", "Centre-back", "Spain", "La Masia"],
    stats: {
      total: {
        appearances: 111,
        goals: 1,
        assists: 5,
      },
      seasons: [
        {
          season: "2023/24",
          appearances: 32,
          goals: 0,
          assists: 1,
        },
        {
          season: "2024/25",
          appearances: 56,
          goals: 1,
          assists: 4,
        },
        {
          season: "2025/26",
          appearances: 33,
          goals: 1,
          assists: 0,
        },
      ],
    },
  },
  {
    name: "Andreas",
    surname: "CHRISTENSEN",
    shirtNumber: 15,
    position: "Defender",
    age: 29,
    nationality: "Denmark",
    image: "/pictures/first-team/Christensen.webp",
    biography: [
      "Andreas Bødtker Christensen (born 10 April 1996 in Lillerød, Denmark) is a Danish professional footballer who plays as a centre-back for FC Barcelona.",
      "Christensen joined Barcelona in July 2022 after a successful spell at Chelsea, where he won the UEFA Champions League in 2021.",
      "Known for his calmness on the ball, positional awareness, and ability to play out from the back, Christensen has been a reliable presence in Barcelona’s defense.",
    ],
    tags: ["Defender", "Centre-back", "Denmark"],
    stats: {
      total: {
        appearances: 97,
        goals: 5,
        assists: 3,
      },
      seasons: [
        {
          season: "2022/23",
          appearances: 32,
          goals: 1,
          assists: 1,
        },
        {
          season: "2023/24",
          appearances: 42,
          goals: 3,
          assists: 2,
        },
        {
          season: "2024/25",
          appearances: 6,
          goals: 0,
          assists: 0,
        },
        {
          season: "2025/26",
          appearances: 17,
          goals: 1,
          assists: 0,
        },
      ],
    },
  },
  {
    name: "João",
    surname: "CANCELO",
    shirtNumber: 2,
    position: "Defender",
    age: 31,
    nationality: "Portugal",
    image: "/pictures/first-team/Cancelo.webp",
    biography: [
      "João Pedro Cavaco Cancelo (born 27 May 1994 in Barreiro, Portugal) is a Portuguese professional footballer who plays as a defender for FC Barcelona.",
      "Cancelo joined Barcelona in January 2026 from Al-Hilal SFC. He is known for his technical ability, versatility, and attacking prowess as a full-back, having previously won multiple Premier League titles with Manchester City and domestic trophies with Benfica and Juventus.",
      "A full international for Portugal since 2016, Cancelo has earned over 60 caps for his country. At Barcelona, he is valued for his experience and ability to play on either flank, contributing to the team's build-up play.",
    ],
    tags: ["Defender", "Right-back", "Portugal"],
    stats: {
      total: {
        appearances: 48,
        goals: 4,
        assists: 6,
      },
      seasons: [
        {
          season: "2025/26",
          appearances: 6,
          goals: 0,
          assists: 1,
        },
        {
          season: "2023/24",
          appearances: 42,
          goals: 4,
          assists: 5,
        },
      ],
    },
  },
  {
    name: "Gerard",
    surname: "MARTÍN",
    shirtNumber: 18,
    position: "Defender",
    age: 24,
    nationality: "Spain",
    image: "/pictures/first-team/Martin.webp",
    biography: [
      "Gerard Martín Langreo (born 26 February 2002 in Esparreguera, Spain) is a Spanish professional footballer who plays as a left-back for FC Barcelona.",
      "A product of La Masia, Martín progressed through the youth ranks and made his first-team debut in 2023. He is known for his defensive solidity, work rate, and ability to contribute to the attack from the flank.",
      "Since breaking into the senior squad, Martín has established himself as a reliable option at left-back, providing depth and versatility to Barcelona's defense.",
    ],
    tags: ["Defender", "Left-back", "Spain", "La Masia"],
    stats: {
      total: {
        appearances: 77,
        goals: 1,
        assists: 6,
      },
      seasons: [
        {
          season: "2024/25",
          appearances: 42,
          goals: 1,
          assists: 6,
        },
        {
          season: "2025/26",
          appearances: 35,
          goals: 0,
          assists: 0,
        },
      ],
    },
  },
  {
    name: "Jules",
    surname: "KOUNDÉ",
    shirtNumber: 23,
    position: "Defender",
    age: 27,
    nationality: "France",
    image: "/pictures/first-team/Kounde.webp",
    biography: [
      "Jules Olivier Koundé (born 12 November 1998 in Paris, France) is a French professional footballer who plays as a defender for FC Barcelona [citation:1].",
      "Koundé joined Barcelona in July 2022 from Sevilla, where he had previously won the UEFA Europa League in 2020. A key figure for both club and country, he was a runner-up with France at the 2022 FIFA World Cup [citation:1][citation:2].",
      "Primarily a right-back at Barcelona, he is also capable of playing as a centre-back. He is known for his defensive quickness, ability on the ball, and was crucial in helping Barça secure the 2022/23 La Liga title and the 2025 Copa del Rey, where he scored the winning goal in the final [citation:1][citation:2].",
    ],
    tags: ["Defender", "Right-back", "France"],
    stats: {
      total: {
        appearances: 179,
        goals: 10,
        assists: 21,
      },
      seasons: [
        {
          season: "2022/23",
          appearances: 40,
          goals: 1,
          assists: 6,
        },
        {
          season: "2023/24",
          appearances: 48,
          goals: 2,
          assists: 4,
        },
        {
          season: "2024/25",
          appearances: 53,
          goals: 4,
          assists: 8,
        },
        {
          season: "2025/26",
          appearances: 38,
          goals: 3,
          assists: 3,
        },
      ],
    },
  },
  {
    name: "Eric",
    surname: "GARCÍA",
    shirtNumber: 24,
    position: "Defender",
    age: 25,
    nationality: "Spain",
    image: "/pictures/first-team/Eric_Garcia.webp",
    biography: [
      "Eric García Martret (born 9 January 2001 in Martorell, Spain) is a Spanish professional footballer who plays as a defender for FC Barcelona [citation:8].",
      "A product of La Masia, he returned to Barcelona in the summer of 2021 from Manchester City after a successful loan spell at Girona during the 2023–24 campaign helped restore his confidence [citation:1][citation:8]. He signed a contract extension with the club in December 2025, keeping him at Barça until 2031 [citation:9].",
      "Known for his calmness on the ball, positional awareness, and ability to play out from the back, Eric has become indispensable under Hansi Flick due to his versatility, performing reliably as a centre-back, defensive Midfielder, and even at right-back [citation:1][citation:5]. He has featured in every official match for Barcelona so far in the 2025/26 season [citation:1].",
    ],
    tags: ["Defender", "Centre-back", "Spain", "La Masia"],
    stats: {
      total: {
        appearances: 154,
        goals: 7,
        assists: 6,
      },
      seasons: [
        {
          season: "2021/22",
          appearances: 36,
          goals: 0,
          assists: 0,
        },
        {
          season: "2022/23",
          appearances: 32,
          goals: 1,
          assists: 2,
        },
        {
          season: "2023/24",
          appearances: 2,
          goals: 0,
          assists: 0,
        },
        {
          season: "2024/25",
          appearances: 45,
          goals: 5,
          assists: 3,
        },
        {
          season: "2025/26",
          appearances: 39,
          goals: 1,
          assists: 1,
        },
      ],
    },
  },
  {
    name: "Pablo",
    surname: "GAVI",
    shirtNumber: 6,
    position: "Midfielder",
    age: 21,
    nationality: "Spain",
    image: "/pictures/first-team/Gavi.webp",
    biography: [
      "Pablo Martín Páez Gavira 'Gavi' (born 5 August 2004 in Los Palacios y Villafranca, Spain) is a Spanish professional footballer who plays as a central Midfielder for FC Barcelona.",
      "A product of La Masia after joining in 2015, he made his first-team debut in August 2021 at just 17 years old. In 2022, he was awarded both the Golden Boy and the Kopa Trophy, recognizing him as the best under-21 player in the world.",
      "Known for his tenacity, technical ability, and winning character, Gavi suffered a serious knee injury in November 2023 but returned to action in October 2024. He signed a contract extension with Barcelona in January 2025, keeping him at the club until 2030.",
    ],
    tags: ["Midfielder", "Central Midfielder", "Spain", "La Masia"],
    stats: {
      total: {
        appearances: 155,
        goals: 10,
        assists: 15,
      },
      seasons: [
        {
          season: "2021/22",
          appearances: 47,
          goals: 2,
          assists: 5,
        },
        {
          season: "2022/23",
          appearances: 49,
          goals: 3,
          assists: 6,
        },
        {
          season: "2023/24",
          appearances: 15,
          goals: 2,
          assists: 1,
        },
        {
          season: "2024/25",
          appearances: 42,
          goals: 3,
          assists: 2,
        },
        {
          season: "2025/26",
          appearances: 2,
          goals: 0,
          assists: 1,
        },
      ],
    },
  },
  {
    name: "Pedro",
    surname: "GONZÁLEZ",
    shirtNumber: 8,
    position: "Midfielder",
    age: 23,
    nationality: "Spain",
    image: "/pictures/first-team/Pedri.webp",
    biography: [
      "Pedro González López 'Pedri' (born 25 November 2002 in Tegueste, Tenerife, Spain) is a Spanish professional footballer who plays as a central Midfielder for FC Barcelona [citation:3][citation:4].",
      "A product of Las Palmas' youth system, he joined Barcelona in 2020 and quickly established himself as one of the world's best young Midfielders. In 2021, he was awarded both the Golden Boy and the Kopa Trophy, recognizing him as the best under-21 player in the world [citation:1][citation:10].",
      "Known for his exceptional vision, passing range, and composure on the ball, Pedri has been a key figure for both club and country. He won the UEFA European Championship with Spain in 2024 and has collected multiple trophies with Barcelona, including La Liga (2022/23), two Copas del Rey, and two Supercopas de España [citation:1][citation:4].",
    ],
    tags: ["Midfielder", "Central Midfielder", "Spain"],
    stats: {
      total: {
        appearances: 228,
        goals: 28,
        assists: 29,
      },
      seasons: [
        {
          season: "2020/21",
          appearances: 52,
          goals: 4,
          assists: 6,
        },
        {
          season: "2021/22",
          appearances: 22,
          goals: 5,
          assists: 1,
        },
        {
          season: "2022/23",
          appearances: 35,
          goals: 7,
          assists: 1,
        },
        {
          season: "2023/24",
          appearances: 34,
          goals: 4,
          assists: 5,
        },
        {
          season: "2024/25",
          appearances: 59,
          goals: 6,
          assists: 8,
        },
        {
          season: "2025/26",
          appearances: 25,
          goals: 2,
          assists: 8,
        },
      ],
    },
  },
  {
    name: "Fermin",
    surname: "LOPEZ",
    shirtNumber: 16,
    position: "Midfielder",
    age: 23,
    nationality: "Spain",
    image: "/pictures/first-team/Fermin.webp",
    biography: [
      "Fermín López Marín (born 11 May 2003 in El Campillo, Spain) is a Spanish professional footballer who plays as a Midfielder for FC Barcelona.",
      "A product of La Masia, he made his first-team debut in 2023 and quickly became known for his late runs into the box, powerful shooting, and goal-scoring ability from midfield.",
      "Fermín has been praised for his work ethic and versatility in the center of the park, contributing both goals and assists in his breakthrough seasons.",
    ],
    tags: ["Midfielder", "Central Midfielder", "Spain", "La Masia"],
    stats: {
      total: {
        appearances: 99,
        goals: 30,
        assists: 21,
      },
      seasons: [
        {
          season: "2023/24",
          appearances: 42,
          goals: 11,
          assists: 0,
        },
        {
          season: "2024/25",
          appearances: 35,
          goals: 8,
          assists: 9,
        },
        {
          season: "2025/26",
          appearances: 22,
          goals: 11,
          assists: 12,
        },
      ],
    },
  },
  {
    name: "Marc",
    surname: "CASADO",
    shirtNumber: 17,
    position: "Midfielder",
    age: 22,
    nationality: "Spain",
    image: "/pictures/first-team/Casado.webp",
    biography: [
      "Marc Casadó Torras (born 14 September 2003 in Sant Pere de Vilamajor, Spain) is a Spanish professional footballer who plays as a Midfielder for FC Barcelona.",
      "A product of La Masia, he made his first-team debut in 2022 and has established himself as a versatile defensive Midfielder known for his tactical intelligence and passing ability.",
      "Casadó has been praised for his work rate and ability to break up play, becoming a reliable option in Barcelona's midfield rotation.",
    ],
    tags: ["Midfielder", "Defensive Midfielder", "Spain", "La Masia"],
    stats: {
      total: {
        appearances: 66,
        goals: 1,
        assists: 7,
      },
      seasons: [
        {
          season: "2022/23",
          appearances: 1,
          goals: 0,
          assists: 0,
        },
        {
          season: "2023/24",
          appearances: 4,
          goals: 0,
          assists: 0,
        },
        {
          season: "2024/25",
          appearances: 36,
          goals: 1,
          assists: 6,
        },
        {
          season: "2025/26",
          appearances: 25,
          goals: 0,
          assists: 1,
        },
      ],
    },
  },
  {
    name: "Frenkie",
    surname: "DE JONG",
    shirtNumber: 21,
    position: "Midfielder",
    age: 29,
    nationality: "Netherlands",
    image: "/pictures/first-team/De_Jong.webp",
    biography: [
      "Frenkie de Jong (born 12 May 1997 in Gorinchem, Netherlands) is a Dutch professional footballer who plays as a Midfielder for FC Barcelona and serves as one of the club's captains [citation:5].",
      "De Jong joined Barcelona in July 2019 from Ajax for €75 million after a breakthrough 2018-19 season where he won the Eredivisie, reached the Champions League semi-finals, and was named UEFA Midfielder of the Season [citation:1][citation:5].",
      "Known for his exceptional ball control, vision, passing range, and ability to progress the ball through midfield, De Jong has been a key figure for Barcelona since his arrival. He has won multiple trophies with the club including La Liga (2022-23), two Copas del Rey, and three Supercopas de España [citation:5][citation:8].",
    ],
    tags: ["Midfielder", "Central Midfielder", "Netherlands", "Captain"],
    stats: {
      total: {
        appearances: 290,
        goals: 20,
        assists: 28,
      },
      seasons: [
        {
          season: "2019/20",
          appearances: 42,
          goals: 2,
          assists: 3,
        },
        {
          season: "2020/21",
          appearances: 51,
          goals: 7,
          assists: 7,
        },
        {
          season: "2021/22",
          appearances: 47,
          goals: 4,
          assists: 5,
        },
        {
          season: "2022/23",
          appearances: 43,
          goals: 2,
          assists: 4,
        },
        {
          season: "2023/24",
          appearances: 30,
          goals: 2,
          assists: 0,
        },
        {
          season: "2024/25",
          appearances: 46,
          goals: 2,
          assists: 2,
        },
        {
          season: "2025/26",
          appearances: 31,
          goals: 1,
          assists: 7,
        },
      ],
    },
  },
  {
    name: "Dani",
    surname: "OLMO",
    shirtNumber: 20,
    position: "Midfielder",
    age: 27,
    nationality: "Spain",
    image: "/pictures/first-team/Olmo.webp",
    biography: [
      "Dani Olmo Carvajal (born 7 May 1998 in Terrassa, Spain) is a Spanish professional footballer who plays as an attacking Midfielder for FC Barcelona.",
      "A product of La Masia, he left for Dinamo Zagreb in 2014 to gain first-team experience, where he developed into a creative force. He later starred at RB Leipzig before returning to Barcelona in the summer of 2024.",
      "Olmo is known for his dribbling, vision, and goal-scoring ability from midfield. He has been a key contributor for Spain, winning the 2024 UEFA European Championship.",
    ],
    tags: ["Midfielder", "Attacking Midfielder", "Spain", "La Masia"],
    stats: {
      total: {
        appearances: 70,
        goals: 19,
        assists: 12,
      },
      seasons: [
        {
          season: "2024/25",
          appearances: 39,
          goals: 12,
          assists: 6,
        },
        {
          season: "2025/26",
          appearances: 31,
          goals: 7,
          assists: 6,
        },
      ],
    },
  },
  {
    name: "Marc",
    surname: "BERNAL",
    shirtNumber: 22,
    position: "Midfielder",
    age: 18,
    nationality: "Spain",
    image: "/pictures/first-team/Bernal.webp",
    biography: [
      "Marc Bernal Casas (born 26 May 2007 in Berga, Spain) is a Spanish professional footballer who plays as a defensive Midfielder for FC Barcelona [citation:2][citation:5].",
      "A product of La Masia since 2014, he made his first-team debut in August 2024 under Hansi Flick but suffered a serious ACL injury that sidelined him for over a year [citation:1][citation:3]. He returned in September 2025 and signed a contract extension until 2029 with a €500 million release clause [citation:1][citation:6].",
      "Known for his positioning, game intelligence, and passing ability, Bernal has drawn comparisons to Sergio Busquets [citation:3][citation:9]. He scored his first senior goal for Barcelona in February 2026 against Mallorca [citation:4][citation:8].",
    ],
    tags: ["Midfielder", "Defensive Midfielder", "Spain", "La Masia"],
    stats: {
      total: {
        appearances: 23,
        goals: 2,
        assists: 1,
      },
      seasons: [
        {
          season: "2024/25",
          appearances: 3,
          goals: 0,
          assists: 0,
        },
        {
          season: "2025/26",
          appearances: 20,
          goals: 2,
          assists: 1,
        },
      ],
    },
  },
  {
    name: "Ferran",
    surname: "TORRES",
    shirtNumber: 7,
    position: "Forward",
    age: 26,
    nationality: "Spain",
    image: "/pictures/first-team/Ferran_Torres.webp",
    biography: [
      "Ferran Torres García (born 29 February 2000 in Foios, Spain) is a Spanish professional footballer who plays as a Forward for FC Barcelona [citation:1].",
      "A product of Valencia's academy, he made history as the first player born in the 21st century to debut in La Liga [citation:1]. After starring at Valencia and Manchester City, he joined Barcelona in January 2022 [citation:1].",
      "Known for his versatility across the front line, finishing ability, and work rate, Torres has been a key contributor for Barcelona. The 2024/25 season was his best statistically with 19 goals, finishing as the Copa del Rey top scorer with 6 goals and being named Man of the Match in the final against Real Madrid [citation:1]. He is also a European champion with Spain, winning Euro 2024 [citation:1].",
    ],
    tags: ["Forward", "Winger", "Spain"],
    stats: {
      total: {
        appearances: 192,
        goals: 60,
        assists: 20,
      },
      seasons: [
        {
          season: "2021/22",
          appearances: 26,
          goals: 7,
          assists: 6,
        },
        {
          season: "2022/23",
          appearances: 45,
          goals: 7,
          assists: 3,
        },
        {
          season: "2023/24",
          appearances: 42,
          goals: 11,
          assists: 3,
        },
        {
          season: "2024/25",
          appearances: 45,
          goals: 19,
          assists: 7,
        },
        {
          season: "2025/26",
          appearances: 34,
          goals: 16,
          assists: 1,
        },
      ],
    },
  },
  {
    name: "Robert",
    surname: "LEWANDOWSKI",
    shirtNumber: 9,
    position: "Forward",
    age: 37,
    nationality: "Poland",
    image: "/pictures/first-team/Lewandowski.webp",
    biography: [
      "Robert Lewandowski (born 21 August 1988 in Warsaw, Poland) is a Polish professional footballer who plays as a striker for FC Barcelona and captains the Poland national team [citation:1].",
      "Widely regarded as one of the greatest strikers of all time, he joined Barcelona in July 2022 from Bayern Munich, where he won the Bundesliga in each of his eight seasons and the Champions League in 2020 as part of a treble [citation:1]. He is one of only five players to have scored 100 goals with three different clubs and ranks third for all-time top goalscorers in the UEFA Champions League [citation:1].",
      "Known for his incredible goal-scoring consistency, positioning, and technique, Lewandowski won the Pichichi Trophy in his debut La Liga season (2022/23) and helped Barcelona win the league title that same year. He has been named the Best FIFA Men's Player twice (2020, 2021) and won the European Golden Shoe for the 2020-21 and 2021-22 seasons [citation:1].",
    ],
    tags: ["Forward", "Striker", "Poland", "Captain"],
    stats: {
      total: {
        appearances: 178,
        goals: 114,
        assists: 21,
      },
      seasons: [
        {
          season: "2022/23",
          appearances: 46,
          goals: 33,
          assists: 8,
        },
        {
          season: "2023/24",
          appearances: 49,
          goals: 26,
          assists: 9,
        },
        {
          season: "2024/25",
          appearances: 52,
          goals: 42,
          assists: 3,
        },
        {
          season: "2025/26",
          appearances: 26,
          goals: 13,
          assists: 1,
        },
      ],
    },
  },
  {
    name: "Raphinha",
    surname: "DIAS BELLOLI",
    shirtNumber: 11,
    position: "Forward",
    age: 29,
    nationality: "Brazil",
    image: "/pictures/first-team/Raphinha.webp",
    biography: [
      "Raphael Dias Belloli 'Raphinha' (born 14 December 1996 in Porto Alegre, Brazil) is a Brazilian professional footballer who plays as a Forward for FC Barcelona and serves as one of the club's vice-captains.",
      "Raphinha joined Barcelona in July 2022 from Leeds United after impressing in the Premier League. Initially used as a traditional winger, he was transformed under Hansi Flick into a more central attacking role, becoming one of the world's most lethal Forwards.",
      "Known for his explosive pace, dribbling ability, and clinical finishing, Raphinha had a historic 2024/25 season with 34 goals and 25 assists, finishing as the UEFA Champions League top scorer and placing 5th in the 2025 Ballon d'Or. He has won multiple trophies with Barcelona including La Liga (2022/23, 2024/25), two Copas del Rey, and two Supercopas de España.",
    ],
    tags: ["Forward", "Winger", "Brazil", "Captain"],
    stats: {
      total: {
        appearances: 168,
        goals: 67,
        assists: 50,
      },
      seasons: [
        {
          season: "2022/23",
          appearances: 50,
          goals: 10,
          assists: 12,
        },
        {
          season: "2023/24",
          appearances: 37,
          goals: 10,
          assists: 11,
        },
        {
          season: "2024/25",
          appearances: 57,
          goals: 34,
          assists: 22,
        },
        {
          season: "2025/26",
          appearances: 24,
          goals: 13,
          assists: 5,
        },
      ],
    },
  },
  {
    name: "Lamine",
    surname: "YAMAL NASRAOUI EBANA",
    shirtNumber: 10,
    position: "Forward",
    age: 18,
    nationality: "Spain",
    image: "/pictures/first-team/Lamine.webp",
    biography: [
      "Lamine Yamal Nasraoui Ebana (born 13 July 2007 in Esplugues de Llobregat, Spain) is a Spanish professional footballer who plays as a Forward for FC Barcelona .",
      "A product of La Masia, he made his first-team debut in April 2023 at just 15 years old, becoming the youngest player to appear for Barcelona in over a century . In 2025, he became the first player to win the Kopa Trophy twice and finished second in the Ballon d'Or rankings .",
      "Known for his flair, chance creation, and long-distance curling goals, Yamal was instrumental in Barcelona's domestic treble in 2024/25 and Spain's Euro 2024 victory. He inherited the iconic number 10 jersey for the 2025/26 season .",
    ],
    tags: ["Forward", "Winger", "Spain", "La Masia"],
    stats: {
      total: {
        appearances: 138,
        goals: 40,
        assists: 41,
      },
      seasons: [
        {
          season: "2022/23",
          appearances: 3,
          goals: 0,
          assists: 0,
        },
        {
          season: "2023/24",
          appearances: 50,
          goals: 7,
          assists: 7,
        },
        {
          season: "2024/25",
          appearances: 55,
          goals: 18,
          assists: 21,
        },
        {
          season: "2025/26",
          appearances: 33,
          goals: 15,
          assists: 13,
        },
      ],
    },
  },

  {
    name: "Marcus",
    surname: "RASHFORD",
    shirtNumber: 14,
    position: "Forward",
    age: 28,
    nationality: "England",
    image: "/pictures/first-team/Rashford.webp",
    biography: [
      "Marcus Rashford (born 31 October 1997 in Manchester, England) is an English professional footballer who plays as a Forward for FC Barcelona on loan from Manchester United [citation:7].",
      "A product of Manchester United's academy, he made his debut in 2016 and went on to make over 400 appearances, winning two FA Cups, two EFL Cups, and the Europa League [citation:7][citation:10]. He joined Barcelona on a season-long loan in the summer of 2025 after falling out of favor at Old Trafford [citation:1][citation:2].",
      "Known for his pace, dribbling ability, and direct running at defenders, Rashford has rediscovered his best form under Hansi Flick. Barcelona have agreed to make his move permanent for €30 million, with Rashford accepting a significant pay cut to stay at the Camp Nou [citation:1][citation:2][citation:5].",
    ],
    tags: ["Forward", "Winger", "England"],
    stats: {
      total: {
        appearances: 34,
        goals: 10,
        assists: 10,
      },
      seasons: [
        {
          season: "2025/26",
          appearances: 34,
          goals: 10,
          assists: 10,
        },
      ],
    },
  },
  {
    name: "Roony",
    surname: "BARDGHJI",
    shirtNumber: 28,
    position: "Forward",
    age: 20,
    nationality: "Sweden",
    image: "/pictures/first-team/Bardghji.webp",
    biography: [
      "Roony Bardghji (born 15 November 2005 in Kuwait City, Kuwait) is a Swedish professional footballer who plays as a Forward for FC Barcelona [citation:1][citation:4].",
      "Born to Syrian parents in Kuwait, he moved to Sweden with his family in 2012 and began his career at Malmö FF before joining FC Copenhagen in 2020. At 16, he became the youngest debutant in Copenhagen's history and gained international recognition after scoring the winning goal against Manchester United in the 2023 Champions League [citation:4][citation:9].",
      "After suffering a serious ACL injury in May 2024, Barcelona signed him in July 2025 for €2 million. Initially registered with Barça Atlètic, he quickly broke into the first team under Hansi Flick, making his La Liga debut against Valencia in September 2025. Known for his dribbling, speed, and left-footed cutting inside from the right wing, Bardghji has been compared to Messi and now wears the number 28 shirt [citation:3][citation:4][citation:8].",
    ],
    tags: ["Forward", "Winger", "Sweden"],
    stats: {
      total: {
        appearances: 20,
        goals: 2,
        assists: 4,
      },
      seasons: [
        {
          season: "2025/26",
          appearances: 20,
          goals: 2,
          assists: 4,
        },
      ],
    },
  },
];
